# Dr Brian Mitchell training data.

PATIENT_GREETINGS = {
  'type' => :greeting,
  'data' => [
    'Hi Doctor.',
    'Hey Doc',
    'Hi Doc',
    'Hi Dr.',
    'Hi there!',
    'Hiya',
    'Hiya!',
    'Hiya :)',
    'Hiya there',
    'Hi Dr!',
    'Greetings',
    'Hello',
    'Hi',
    'Hi :D',
    'Hi!',
    'Hi.',
    'Hi :)',
    'Hiiii',
    'Hiii!',
    'Hey.',
    'Heyyyyyy',
    'Hi!!',
    'Yooyooyooyoyoy bboy',
    'YO!',
    'Hello',
    'Hello Doc',
    'Hello Doctor!',
    'Hello Doctor',
    'Hello Dr.',
    'Hello!',
    'Hi Doctor!',
    'Yo Doctor!',
    'Yo Doctor',
    'Hi there.',
    'Hi there.',
    'Yo',
    'How are you?',
    'How are you.',
    'How are things with your patients?',
    'How are you doing?',
    'How are you today?',
    'How is it going?',
    'How are things?',
    'Hi there',
    'Hey',
    'How ya doin?',
    'How is everything?',
    "How's everything going?",
    'Hey Doctor.',
    'Hi',
    'Good morning.',
    'Good afternoon.',
    'Good evening.',
    'Good Morning Doctor.',
    'Good afternoon Doctor.',
    'Good evening Doctor.',
    'How are you?',
    'How are you Doctor?'
  ]
}.freeze

PATIENT_QUESTION = {
  'type' => :question,
  'data' => [
    'How can I get rid of this?',
    'How could I have gotten this?',
    'Is it something serious?',
    'How long do I have to stay in hospital?',
    'how can I get rid of this?',
    'How effective is this treatment?',
    'Is there anything I should stop or avoid doing?',
    'Is there anything I can do to help myself?',
    "What will happen if I don’t have any treatment?",
    'How effective is this treatment?',
    'How will I know if the treatment is working?',
    'How long will I need treatment for?',
    'Are there any side effects or risks? If so, what are they?',
    'Are there other ways to treat my condition?',
    'Where can I go for more information?',
    'What do you recommend?',
    'What do you recommend Doctor',
    'Do you think?',
    'How can I be a better person?',
    'Advice?',
    'Tips?',
    'think I should',
    'do you think I should',
    'Please recommend me!',
    'What do you think?',
    'Any tips?',
    'How does this',
    'How does this compare',
    'do you?',
    'do you think?',
    'Thanks,',
    'How is this bad?',
    'What is the',
    'What is',
    'What is...',
    'What',
    'Health tips?',
    'What do you think about this?',
    "What happens if I don't get better?",
    'Do I have to be operated on?',
    'What do I do?',
    'What position should I sleep in?',
    'Will I need surgery?',
    'Could you check again?',
    'Is it something serious?',
    'Is this a common problem at my age?',
    'Is this a common problem?',
    "What happens if I don't get better?"
  ]
}.freeze

GREETINGS = {
  'type' => :greeting,
  'data' => [
    'Hey *, how is everything?',
    "Hi *, how's everything going?",
    'Good morning!',
    'Good morning *.',
    'Good afternoon!',
    'Good afternoon *.',
    'Good evening!',
    'Good evening *.',
    'Hi *, :)',
    'Hello *! :)',
    'Hi there *. :)',
    'Hello there, what can I do for you?',
    'Hello there *, what can I do for you?',
    "Hi *, How's everything going?",
    "Hey there, How's it going?",
    "Hey there *, How's it going?",
    'Hi there, How are you today?',
    'Good to see you *.',
    'Hello *, Could you tell your issues today?',
    "Hi *, What's your issue?",
    'Hi *, How are you?',
    'Hi *, How are you today?',
    'Well hello!',
    'Yes?',
    'Morning!',
    "I'm quite fine, thanks!",
    'Hello there!',
    'Hello there, whats the problem?',
    'Hi!',
    'Hi *!',
    'Hello?',
    'Hi *.',
    'How are you today?',
    "Hey, what's the issue?",
    'How are you feeling today?',
    'Hello',
    'Hello *!',
    'Hello, how can I help you?',
    'Hello *, how can I help you?',
    'How can I help you today?'
  ]
}.freeze

THANKS = {
  'type' => :thanks,
  'data' => [
    'Thanks',
    'Thanks Doc!',
    'Thanks Doctor!',
    'Thanks Doc.',
    'Thank you Doctor.',
    'Thank you Doc!',
    'Thank you Doc!',
    'Thanks alot!',
    "That's very helpful, Thank you!",
    'Thanks!',
    "That's helpful, thank you.",
    'Thank you very much!',
    'Thanks very much!',
    'Oh Thanks',
    'Oh Thanks.',
    'Oh,Thanks!',
    'Thanks very much',
    'Thank so much',
    'Thank you Dr.',
    'Thank you Dr!',
    'Thank you Doc.',
    'Thank you for everything Doctor!',
    'Thank you so much Doctor!',
    'No thanks for your help',
    'OK! Thank you!',
    'OK! Thanks!'
  ]
}.freeze

UNSURE = {
  'type' => :unsure,
  'data' => [
    "I'm not sure about this.",
    "I'm not so sure.",
    "I don't know.",
    'not that I know of',
    "I quite don't know.",
    "I don't quite know.",
    'what did you say?',
    'what you mean?',
    "I'm not quite sure what you mean.",
    "I'm not quite sure what you mean?",
    'what do you mean?',
    'What are you talking about?',
    'Please clarify',
    'you sure?',
    'Why no.',
    "I'm trying to understand",
    'failing to',
    'w.t.f',
    'What are you saying?',
    'wat.',
    'valid',
    "I'm sorry, what?",
    'invalid',
    'wat',
    "I don't understand",
    'WTF?',
    "I'm not sure",
    "don't know",
    'nowt',
    'unsure',
    "I'm unsure",
    'hmmmmm.',
    'ugh.',
    'err',
    '?',
    '??',
    '???',
    '????',
    'why?',
    'why',
    'ugh',
    'err..',
    'I cannot comprehend',
    'what you are saying',
    "what you're",
    'making any sense?',
    'random',
    ':S',
    'idk',
    'wat?',
    'Wht?',
    'umm',
    'so',
    'so...',
    'huh?',
    'abcdefghijklmnopqrstuvwxyz'
  ]
}.freeze

NEGATIVE = {
  'type' => :negative,
  'data' => [
    'I am sick',
    '...',
    'no',
    'not working',
    "You're a bot",
    'I feel',
    'I have chest pain',
    'I have pains',
    'sore',
    'suffer from',
    'I have lots of pain.',
    'pain',
    'cut',
    'broken',
    'fracture',
    'swollen',
    'black eye',
    'dizzy',
    'sick',
    'nausaous',
    'weaker',
    'sprained',
    'vomit',
    'swelling',
    'swollen',
    'attack',
    'tired',
    'depressed',
    'sprain',
    'cramps',
    'disease',
    'attack',
    'stroke',
    'bad',
    'dead',
    'dumb',
    'f*ck',
    'pale',
    'nasty',
    'sh*t',
    'weak',
    'weaker',
    'I have pain',
    'I feel pain',
    'I have pain in the',
    'I feel pain near',
    'crap',
    'I suffer from',
    "I'm suffering",
    'I suffering from',
    "I'm suffering right now",
    'I suffer',
    'depression',
    'ache',
    'feeling under the weather',
    'allergic reaction',
    'dry',
    'high',
    'exausted',
    'shattered',
    'runny',
    'runny nose',
    'problem',
    'upset',
    'lost appitite',
    'headache',
    'sharp pain',
    'light pain',
    'splitting',
    'headache',
    'unwell',
    'depressed',
    'This illness is annoying',
    'I have a nasty cold',
    'Nothing has changed.',
    "I'm quite fustrated",
    'I am not feeling well',
    'I am unwell',
    'Not a chance',
    'I am worried',
    'high risk',
    'forget it',
    'no help at all.',
    'problem',
    'troll',
    'Nope',
    'Not',
    'NOT',
    'Negative',
    'Not cool',
    'Stop',
    "It's getting worse",
    'I am seriously ill',
    'its not working.',
    'illness',
    'hate',
    'I hate this',
    'I have a bad cough',
    'Please help me.',
    ':(',
    'Not good',
    '>:(',
    "I don't even",
    "I can't even",
    "I can't",
    'Wrong'
  ]
}.freeze

POSITIVE = {
  'type' => :positive,
  'data' => [
    'Your a lifesaver',
    'I have no problems',
    'good',
    'nice',
    'great',
    'Excellent',
    'sweet',
    'low risk',
    ':)',
    ':O',
    'LOL',
    'LMAO',
    ';)',
    ':D',
    'Cool!',
    '+1',
    ':P',
    "I'm fine!",
    "I'm feeling great!",
    'never been better',
    'your tips is brillant',
    'that worked',
    "I'm getting better"
  ]
}.freeze

ANSWER = {
  'type' => :answer,
  'data' => [
    'Yes',
    'No',
    'No.',
    'Nope',
    'Not at all',
    'Nop',
    'understood',
    'No.',
    'Yep',
    'I dont do',
    'anything',
    'I do',
    'take',
    'I Do'
  ]
}.freeze

DR_UNSURE = {
  'type' => :unsure,
  'data' => [
    '??????',
    'Err, What are you saying?.',
    "I don't get what you mean",
    "I don't quite get what you mean?",
    "I'm sorry, but you're not making any sense.",
    'Do you have any questions??',
    'Do you need any help?',
    "I'm trying to understand.",
    "I'm failing to understand what you're saying.",
    "I'm sorry, what?",
    "What you're saying isn't making sense.",
    "I'm afraid I don't understand.",
    'Please clarify.',
    'Are you making any sense?',
    "I don't think you're making sense.",
    'What are you trying to say?',
    "I'm not quite sure what you mean?"
  ]
}.freeze
